language: python

dist: xenial

sudo:
  - false
  - true


python:
  - 3.7
  - 3.6

env:
  matrix:
    - ID=R314_ARRAY INSTALL_NUMPY=0 PACKAGED_DEPS=0.8.2/epics-ci-0.8.2_R3.14.12.6_pva_areadetector3-2_motor6-9.tar.bz2
    - ID=R314_NUMPY INSTALL_NUMPY=1 PACKAGED_DEPS=0.8.2/epics-ci-0.8.2_R3.14.12.6_pva_areadetector3-2_motor6-9.tar.bz2
    - ID=R7_NUMPY INSTALL_NUMPY=1 PUBLISH_DOCS=1 PACKAGED_DEPS=0.8.2/epics-ci-0.8.2_R7.0.1.1_pva_areadetector3-2_motor6-10.tar.bz2
    - ID=R7_ARRAY INSTALL_NUMPY=0 PACKAGED_DEPS=0.8.2/epics-ci-0.8.2_R7.0.1.1_pva_areadetector3-2_motor6-10.tar.bz2

  global:
    - secure: "Hnz9c6x13kaAc7IqH4/wJWNel2rzEC8/x0KhFoGLVLHjmiH1LMmpGh/P5CPADlmKS80WFz4vhJ0YtSjtHCPI+9Y2aBGn8z732WM86OyGHITviCMTxtyVZfRFCkOAVlU0qpIyWu4p0rEfxrXCztSKE4bBO/wWnFhGGw9CJROnFhJwoJlbI9i28zscyeGsdqHNUfXHkyUAN3c3LKoYZgnJco5HiHLwXVvsy3DMkvOizLgslf6lrHwnQOT1F49ShgPcGGWpkuRARXkGII7lB0LOn2TBoTzmhgjoC3OmC4nZGJfzitwH9+nHc+iJ3mTlshsXb366B/D5TNVIL/4rzYV8zw49DogQIWYtECK4/z7fOzG61yCU33b3aeXU2OI4k5eZ2qN3gp3KQ4+PWyCMTHsBVgs6o49K1HWtFuuFLuhUPT4FVs2Pzz6yTka9NUukPO1LoTeQAUvGxRbc/15CjIWXtqqzEGmlPi8AFEo2kw33EtTawMU9w8nzAfdk5DX28Qcuzh9XA9nVUD0j7Rum7nGY1f5+icXh0FsOuP1uHt82bXIYvw3rey3RkWcqVcniJXlkq0bAZM/ZSXWX5VHyQ2e7C4kxCdnzVqjgtlGT2ARSlD6o8FKKRKTAKD7kQ9ajTjZHRhO+xbvP+X4K9GlbGvPyU9bnDFa14fXBJS4dTMd8GgQ="

matrix:
  exclude:
    - python: 3.6
      sudo: true

    - python: 3.7
      sudo: false

addons:
  apt:
    packages:
      - graphviz  # for building docs
      - procserv

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

before_install:
  - export PATH=/usr/lib/ccache:$PATH

  - git fetch --unshallow
  - export CI_SCRIPTS=${TRAVIS_BUILD_DIR}/.ci/ci-scripts
  - install -d $HOME/epics $HOME/epics/iocs $HOME/epics/support $HOME/epics/base
  - bash .ci/install-from-release.sh "https://github.com/klauer/epics-on-travis/releases/download/${PACKAGED_DEPS}"
  - source $HOME/epics/versions.sh
  - source ${CI_SCRIPTS}/epics-config.sh
  - bash ${CI_SCRIPTS}/run-epics-iocs-on-procserv.sh
  - pip install pyepics numpy

install:
  - pip install .
  - pip install --quiet --upgrade cython

script:
  - caget Py:ao1 sim:mtr1 13SIM1:image1:PluginType_RBV

  # Kill caRepeater if it's running - we want to test caproto-repeater later.
  - pgrep -a caRepeater && killall caRepeater
  - rm -f `which caRepeater`

  - pip install -Ur test-requirements.txt
  - |
    if [ ! $INSTALL_NUMPY ]
    then
      pip uninstall --yes numpy
    fi

  - pip install git+https://github.com/klauer/catvs.git@py3k

  # give us an early warning of flake8 failure
  # the weird quating in to make searching in the results webpage easier
  - flake8 . || echo "flake8 FAI""LED!"
  - caproto-repeater &
  - coverage run --parallel-mode run_tests.py -k 'not bench'  --benchmark-disable -v
  - coverage combine --append

  - export ASV_ENV_NAME=${TRAVIS_PYTHON_VERSION}_${BASE_VER}
  - |
    if [ $INSTALL_NUMPY ]
    then
      coverage run --parallel-mode run_tests.py -v --benchmark-only --benchmark-json=pytest_bench.json --benchmark-columns=mean,median,rounds,iterations -k bench --timeout=50 && coverage combine --append
    fi
  - coverage report -m
  - codecov
  - set -e
  # Install deps for building the docs.
  - pip install --quiet --upgrade --global-option='--without-libyaml' pyyaml
  # directly install second layer deps to work around easy_install bug
  - pip install --quiet cryptography cffi pycparser
  - pip install --quiet --upgrade -r docs-requirements.txt
  # Run a CA Repeater for the docs examples to use.
  - caproto-repeater &
  # Build the docs.
  - pushd doc
  - make html
  - popd
  - flake8

  # Upload the docs to gh-pages.
  - if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'NSLS-II/caproto' && $PUBLISH_DOCS == 1 && $TRAVIS_BRANCH == 'master' ]]; then
        doctr deploy --key-path=doc/github_deploy_key.enc .;
    fi
